name: "PR Title Validator"
description: "Ensure that the PR title follows the Conventional Commits specification"
inputs:
  let-fail:
    description: "Determines if the workflow will fail, otherwise it will just output a boolean (default: true)"
    default: "true"
  skip-prefix:
    description: "Prefix that will skip the validation (default: [WIP]<space>)"
    default: "[WIP] "
  valid-types:
    description: "List of valid conventional commit types"
    default: "feat,fix,build,chore,ci,docs,style,refactor,perf,test"
  valid-scopes:
    description: "List of valid conventional commit scopes (default: empty)"
    default: ""
  max-length:
    description: "Define a maximmal title length"
    default: ""
  regex:
    description: "Regex pattern that defines a valid PR title (empty=default)"
    default: ""
outputs:
  is-valid:
    description: "Indicates if the PR title is a valid conventional commit"
runs:
  using: "node16"
  main: "dist/index.js"
